fix cannot import name '_chmod_and_replace' from 'huggingface_hub.file_download'  (#559)
Hi, Thx for your work!

However, when I run the demo from [Quick
Start](https://github.com/PaddlePaddle/PaddleMIX/blob/develop/applications/README.md/#2%E4%B8%80%E9%94%AE%E9%A2%84%E6%B5%8B):

```
from paddlemix.appflow import Appflow
from ppdiffusers.utils import load_image

task = Appflow(app="openset_det_sam",
                   models=["GroundingDino/groundingdino-swint-ogc","Sam/SamVitH-1024"],
                   static_mode=False) #如果开启静态图推理，设置为True,默认动态图
url = "https://paddlenlp.bj.bcebos.com/models/community/CompVis/stable-diffusion-v1-4/overture-creations.png"
image_pil = load_image(url)
result = task(image=image_pil,prompt="dog")
```

which raise:
```
  File "xxx/Desktop/PaddleMIX/x.py", line 1, in <module>
    from paddlemix.appflow import Appflow
  File "xxx/Desktop/PaddleMIX/paddlemix/__init__.py", line 17, in <module>
    from .models import *
  File "xxx/Desktop/PaddleMIX/paddlemix/models/__init__.py", line 17, in <module>
    from .audioldm2.modeling import *
  File "xxx/Desktop/PaddleMIX/paddlemix/models/audioldm2/modeling.py", line 25, in <module>
    from .latent_encoder.autoencoder import DiagonalGaussianDistribution
  File "xxx/Desktop/PaddleMIX/paddlemix/models/audioldm2/latent_encoder/autoencoder.py", line 18, in <module>
    from ppdiffusers import AutoencoderKL
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/__init__.py", line 17, in <module>
    from .patches import *
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/patches/__init__.py", line 14, in <module>
    from .converter import *
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/patches/converter.py", line 22, in <module>
    from ppdiffusers.transformers.model_utils import ModuleUtilsMixin
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/transformers/__init__.py", line 16, in <module>
    from .auto import *
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/transformers/auto/__init__.py", line 15, in <module>
    from .configuration import *
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/transformers/auto/configuration.py", line 24, in <module>
    from ..model_utils import PretrainedConfig, PretrainedModel
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/transformers/model_utils.py", line 30, in <module>
    from ppdiffusers.utils import (
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/utils/__init__.py", line 72, in <module>
    from .download_utils import (
  File "xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/ppdiffusers/utils/download_utils.py", line 34, in <module>
    from huggingface_hub.file_download import _chmod_and_replace, http_get
ImportError: cannot import name '_chmod_and_replace' from 'huggingface_hub.file_download' (xxx/miniconda3/envs/pp2.6/lib/python3.9/site-packages/huggingface_hub/file_download.py)
```


In the latest version of `huggingface_hub`, `_chmod_and_replace` has
been changed to `_chmod_and_move`.

Here is the link:

https://github.com/huggingface/huggingface_hub/blob/f7cc03622e73d37aab44fb305aa2abbb84782403/src/huggingface_hub/file_download.py#L1904C5-L1904C20

---------

Co-authored-by: xuzhang <westfish@126.com>